import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
import statistics

base_datos = pd.read_csv('proyecto.csv')

##Seleccionamos cada pais##
is_china = base_datos["Country Name"] == "China"
is_alemania = base_datos["Country Name"] == "Alemania"
is_japon = base_datos["Country Name"] == "Japon"
is_reino = base_datos["Country Name"] == "Reino Unido"
is_canada = base_datos["Country Name"] == "Canada"
is_usa = base_datos["Country Name"] == "Estados Unidos"
is_mex = base_datos["Country Name"] == "Mexico"
is_francia = base_datos["Country Name"] == "Francia"
is_brasil = base_datos["Country Name"] == "Brasil"
is_arg = base_datos["Country Name"] == "Argentina"
is_rus = base_datos["Country Name"] == "Federacion de Rusia"
is_esp = base_datos["Country Name"] == "Espana"

##Si necesitamos un año o años especificos modificamos el código

#Año especifico
#is_year = base_datos["Ano"] == ""

#Serie de años
#is_year = base_datos["Ano"].isin["","",""]

ch = base_datos[is_china]
deu = base_datos[is_alemania]
jpn = base_datos[is_japon]
gbr = base_datos[is_reino]
can = base_datos[is_canada]
usa = base_datos[is_usa]
mex = base_datos[is_mex]
fra = base_datos[is_francia]
bra = base_datos[is_brasil]
arg = base_datos[is_arg]
rus = base_datos[is_rus]
esp = base_datos[is_esp]

#ch,deu,jpn,gbr,can,usa,mex,fra,bra,arg,rus,esp
todos = {"Pais":["China","Alemania","Japon","Reino Unido","Canada","Estados Unidos","Mexico","Francia","Brasil","Argentina","Rusia","España"],
         "Balanza minimos": [ch.Balanza_comercial.min(),deu.Balanza_comercial.min(),jpn.Balanza_comercial.min(),gbr.Balanza_comercial.min(),can.Balanza_comercial.min(),usa.Balanza_comercial.min(),mex.Balanza_comercial.min(),fra.Balanza_comercial.min(),bra.Balanza_comercial.min(),arg.Balanza_comercial.min(),rus.Balanza_comercial.min(),esp.Balanza_comercial.min()],
         "Balanza maximos": [ch.Balanza_comercial.max(),deu.Balanza_comercial.max(),jpn.Balanza_comercial.max(),gbr.Balanza_comercial.max(),can.Balanza_comercial.max(),usa.Balanza_comercial.max(),mex.Balanza_comercial.max(),fra.Balanza_comercial.max(),bra.Balanza_comercial.max(),arg.Balanza_comercial.max(),rus.Balanza_comercial.max(),esp.Balanza_comercial.max()],
         "Desempleo min": [ch.Desempleo.min(),deu.Desempleo.min(),jpn.Desempleo.min(),gbr.Desempleo.min(),can.Desempleo.min(),usa.Desempleo.min(),mex.Desempleo.min(),fra.Desempleo.min(),bra.Desempleo.min(),arg.Desempleo.min(),rus.Desempleo.min(),esp.Desempleo.min()],
         "Desempleo max": [ch.Desempleo.max(),deu.Desempleo.max(),jpn.Desempleo.max(),gbr.Desempleo.max(),can.Desempleo.max(),usa.Desempleo.max(),mex.Desempleo.max(),fra.Desempleo.max(),bra.Desempleo.max(),arg.Desempleo.max(),rus.Desempleo.max(),esp.Desempleo.max()],
         "PIB min": [ch.PIB.min(),deu.PIB.min(),jpn.PIB.min(),gbr.PIB.min(),can.PIB.min(),usa.PIB.min(),mex.PIB.min(),fra.PIB.min(),bra.PIB.min(),arg.PIB.min(),rus.PIB.min(),esp.PIB.min()],
         "PIB max": [ch.PIB.max(),deu.PIB.max(),jpn.PIB.max(),gbr.PIB.max(),can.PIB.max(),usa.PIB.max(),mex.PIB.max(),fra.PIB.max(),bra.PIB.max(),arg.PIB.max(),rus.PIB.max(),esp.PIB.max()],
         "Exportaciones_bienes_y_servicios min":[ch.Exportaciones_bienes_y_servicios.min(),deu.Exportaciones_bienes_y_servicios.min(),jpn.Exportaciones_bienes_y_servicios.min(),gbr.Exportaciones_bienes_y_servicios.min(),can.Exportaciones_bienes_y_servicios.min(),usa.Exportaciones_bienes_y_servicios.min(),mex.Exportaciones_bienes_y_servicios.min(),fra.Exportaciones_bienes_y_servicios.min(),bra.Exportaciones_bienes_y_servicios.min(),arg.Exportaciones_bienes_y_servicios.min(),rus.Exportaciones_bienes_y_servicios.min(),esp.Exportaciones_bienes_y_servicios.min()],
         "Exportaciones_bienes_y_servicios max":[ch.Exportaciones_bienes_y_servicios.max(),deu.Exportaciones_bienes_y_servicios.max(),jpn.Exportaciones_bienes_y_servicios.max(),gbr.Exportaciones_bienes_y_servicios.max(),can.Exportaciones_bienes_y_servicios.max(),usa.Exportaciones_bienes_y_servicios.max(),mex.Exportaciones_bienes_y_servicios.max(),fra.Exportaciones_bienes_y_servicios.max(),bra.Exportaciones_bienes_y_servicios.max(),arg.Exportaciones_bienes_y_servicios.max(),rus.Exportaciones_bienes_y_servicios.max(),esp.Exportaciones_bienes_y_servicios.max()],
         "Exportaciones_mercaderias min":[ch.Exportaciones_mercaderias.min(),deu.Exportaciones_mercaderias.min(),jpn.Exportaciones_mercaderias.min(),gbr.Exportaciones_mercaderias.min(),can.Exportaciones_mercaderias.min(),usa.Exportaciones_mercaderias.min(),mex.Exportaciones_mercaderias.min(),fra.Exportaciones_mercaderias.min(),bra.Exportaciones_mercaderias.min(),arg.Exportaciones_mercaderias.min(),rus.Exportaciones_mercaderias.min(),esp.Exportaciones_mercaderias.min()],
         "Exportaciones_mercaderias max":[ch.Exportaciones_mercaderias.max(),deu.Exportaciones_mercaderias.max(),jpn.Exportaciones_mercaderias.max(),gbr.Exportaciones_mercaderias.max(),can.Exportaciones_mercaderias.max(),usa.Exportaciones_mercaderias.max(),mex.Exportaciones_mercaderias.max(),fra.Exportaciones_mercaderias.max(),bra.Exportaciones_mercaderias.max(),arg.Exportaciones_mercaderias.max(),rus.Exportaciones_mercaderias.max(),esp.Exportaciones_mercaderias.max()],
         "Exportaciones_servicios_comerciales min":[ch.Exportaciones_servicios_comerciales.min(),deu.Exportaciones_servicios_comerciales.min(),jpn.Exportaciones_servicios_comerciales.min(),gbr.Exportaciones_servicios_comerciales.min(),can.Exportaciones_servicios_comerciales.min(),usa.Exportaciones_servicios_comerciales.min(),mex.Exportaciones_servicios_comerciales.min(),fra.Exportaciones_servicios_comerciales.min(),bra.Exportaciones_servicios_comerciales.min(),arg.Exportaciones_servicios_comerciales.min(),rus.Exportaciones_servicios_comerciales.min(),esp.Exportaciones_servicios_comerciales.min()],
         "Exportaciones_servicios_comerciales max":[ch.Exportaciones_servicios_comerciales.max(),deu.Exportaciones_servicios_comerciales.max(),jpn.Exportaciones_servicios_comerciales.max(),gbr.Exportaciones_servicios_comerciales.max(),can.Exportaciones_servicios_comerciales.max(),usa.Exportaciones_servicios_comerciales.max(),mex.Exportaciones_servicios_comerciales.max(),fra.Exportaciones_servicios_comerciales.max(),bra.Exportaciones_servicios_comerciales.max(),arg.Exportaciones_servicios_comerciales.max(),rus.Exportaciones_servicios_comerciales.max(),esp.Exportaciones_servicios_comerciales.max()],
         "Importaciones_bienes_y_servicios min":[ch.Importaciones_bienes_y_servicios.min(),deu.Importaciones_bienes_y_servicios.min(),jpn.Importaciones_bienes_y_servicios.min(),gbr.Importaciones_bienes_y_servicios.min(),can.Importaciones_bienes_y_servicios.min(),usa.Importaciones_bienes_y_servicios.min(),mex.Importaciones_bienes_y_servicios.min(),fra.Importaciones_bienes_y_servicios.min(),bra.Importaciones_bienes_y_servicios.min(),arg.Importaciones_bienes_y_servicios.min(),rus.Importaciones_bienes_y_servicios.min(),esp.Importaciones_bienes_y_servicios.min()],
         "Importaciones_bienes_y_servicios max":[ch.Importaciones_bienes_y_servicios.max(),deu.Importaciones_bienes_y_servicios.max(),jpn.Importaciones_bienes_y_servicios.max(),gbr.Importaciones_bienes_y_servicios.max(),can.Importaciones_bienes_y_servicios.max(),usa.Importaciones_bienes_y_servicios.max(),mex.Importaciones_bienes_y_servicios.max(),fra.Importaciones_bienes_y_servicios.max(),bra.Importaciones_bienes_y_servicios.max(),arg.Importaciones_bienes_y_servicios.max(),rus.Importaciones_bienes_y_servicios.max(),esp.Importaciones_bienes_y_servicios.max()],
         "Importaciones_mercaderias min":[ch.Importaciones_mercaderias.min(),deu.Importaciones_mercaderias.min(),jpn.Importaciones_mercaderias.min(),gbr.Importaciones_mercaderias.min(),can.Importaciones_mercaderias.min(),usa.Importaciones_mercaderias.min(),mex.Importaciones_mercaderias.min(),fra.Importaciones_mercaderias.min(),bra.Importaciones_mercaderias.min(),arg.Importaciones_mercaderias.min(),rus.Importaciones_mercaderias.min(),esp.Importaciones_mercaderias.min()],
         "Importaciones_mercaderias max":[ch.Importaciones_mercaderias.max(),deu.Importaciones_mercaderias.max(),jpn.Importaciones_mercaderias.max(),gbr.Importaciones_mercaderias.max(),can.Importaciones_mercaderias.max(),usa.Importaciones_mercaderias.max(),mex.Importaciones_mercaderias.max(),fra.Importaciones_mercaderias.max(),bra.Importaciones_mercaderias.max(),arg.Importaciones_mercaderias.max(),rus.Importaciones_mercaderias.max(),esp.Importaciones_mercaderias.max()],
         "Importaciones_servicios_comerciales min":[ch.Importaciones_servicios_comerciales.min(),deu.Importaciones_servicios_comerciales.min(),jpn.Importaciones_servicios_comerciales.min(),gbr.Importaciones_servicios_comerciales.min(),can.Importaciones_servicios_comerciales.min(),usa.Importaciones_servicios_comerciales.min(),mex.Importaciones_servicios_comerciales.min(),fra.Importaciones_servicios_comerciales.min(),bra.Importaciones_servicios_comerciales.min(),arg.Importaciones_servicios_comerciales.min(),rus.Importaciones_servicios_comerciales.min(),esp.Importaciones_servicios_comerciales.min()],
         "Importaciones_servicios_comerciales max":[ch.Importaciones_servicios_comerciales.max(),deu.Importaciones_servicios_comerciales.max(),jpn.Importaciones_servicios_comerciales.max(),gbr.Importaciones_servicios_comerciales.max(),can.Importaciones_servicios_comerciales.max(),usa.Importaciones_servicios_comerciales.max(),mex.Importaciones_servicios_comerciales.max(),fra.Importaciones_servicios_comerciales.max(),bra.Importaciones_servicios_comerciales.max(),arg.Importaciones_servicios_comerciales.max(),rus.Importaciones_servicios_comerciales.max(),esp.Importaciones_servicios_comerciales.max()],
         "Importaciones_minerales_y_metales min":[ch.Importaciones_minerales_y_metales.min(),deu.Importaciones_minerales_y_metales.min(),jpn.Importaciones_minerales_y_metales.min(),gbr.Importaciones_minerales_y_metales.min(),can.Importaciones_minerales_y_metales.min(),usa.Importaciones_minerales_y_metales.min(),mex.Importaciones_minerales_y_metales.min(),fra.Importaciones_minerales_y_metales.min(),bra.Importaciones_minerales_y_metales.min(),arg.Importaciones_minerales_y_metales.min(),rus.Importaciones_minerales_y_metales.min(),esp.Importaciones_minerales_y_metales.min()],
         "Importaciones_minerales_y_metales max":[ch.Importaciones_minerales_y_metales.max(),deu.Importaciones_minerales_y_metales.max(),jpn.Importaciones_minerales_y_metales.max(),gbr.Importaciones_minerales_y_metales.max(),can.Importaciones_minerales_y_metales.max(),usa.Importaciones_minerales_y_metales.max(),mex.Importaciones_minerales_y_metales.max(),fra.Importaciones_minerales_y_metales.max(),bra.Importaciones_minerales_y_metales.max(),arg.Importaciones_minerales_y_metales.max(),rus.Importaciones_minerales_y_metales.max(),esp.Importaciones_minerales_y_metales.max()],
         "Importaciones_productos_manufacturados min":[ch.Importaciones_productos_manufacturados.min(),deu.Importaciones_productos_manufacturados.min(),jpn.Importaciones_productos_manufacturados.min(),gbr.Importaciones_productos_manufacturados.min(),can.Importaciones_productos_manufacturados.min(),usa.Importaciones_productos_manufacturados.min(),mex.Importaciones_productos_manufacturados.min(),fra.Importaciones_productos_manufacturados.min(),bra.Importaciones_productos_manufacturados.min(),arg.Importaciones_productos_manufacturados.min(),rus.Importaciones_productos_manufacturados.min(),esp.Importaciones_productos_manufacturados.min()],
         "Importaciones_productos_manufacturados max":[ch.Importaciones_productos_manufacturados.max(),deu.Importaciones_productos_manufacturados.max(),jpn.Importaciones_productos_manufacturados.max(),gbr.Importaciones_productos_manufacturados.max(),can.Importaciones_productos_manufacturados.max(),usa.Importaciones_productos_manufacturados.max(),mex.Importaciones_productos_manufacturados.max(),fra.Importaciones_productos_manufacturados.max(),bra.Importaciones_productos_manufacturados.max(),arg.Importaciones_productos_manufacturados.max(),rus.Importaciones_productos_manufacturados.max(),esp.Importaciones_productos_manufacturados.max()],
         "Exportaciones_productos_manufacturados min":[ch.Exportaciones_productos_manufacturados.min(),deu.Exportaciones_productos_manufacturados.min(),jpn.Exportaciones_productos_manufacturados.min(),gbr.Exportaciones_productos_manufacturados.min(),can.Exportaciones_productos_manufacturados.min(),usa.Exportaciones_productos_manufacturados.min(),mex.Exportaciones_productos_manufacturados.min(),fra.Exportaciones_productos_manufacturados.min(),bra.Exportaciones_productos_manufacturados.min(),arg.Exportaciones_productos_manufacturados.min(),rus.Exportaciones_productos_manufacturados.min(),esp.Exportaciones_productos_manufacturados.min()],
         "Exportaciones_productos_manufacturados max":[ch.Exportaciones_productos_manufacturados.max(),deu.Exportaciones_productos_manufacturados.max(),jpn.Exportaciones_productos_manufacturados.max(),gbr.Exportaciones_productos_manufacturados.max(),can.Exportaciones_productos_manufacturados.max(),usa.Exportaciones_productos_manufacturados.max(),mex.Exportaciones_productos_manufacturados.max(),fra.Exportaciones_productos_manufacturados.max(),bra.Exportaciones_productos_manufacturados.max(),arg.Exportaciones_productos_manufacturados.max(),rus.Exportaciones_productos_manufacturados.max(),esp.Exportaciones_productos_manufacturados.max()],
         "Exportaciones_metales_y_minerales min":[ch.Exportaciones_metales_y_minerales.min(),deu.Exportaciones_metales_y_minerales.min(),jpn.Exportaciones_metales_y_minerales.min(),gbr.Exportaciones_metales_y_minerales.min(),can.Exportaciones_metales_y_minerales.min(),usa.Exportaciones_metales_y_minerales.min(),mex.Exportaciones_metales_y_minerales.min(),fra.Exportaciones_metales_y_minerales.min(),bra.Exportaciones_metales_y_minerales.min(),arg.Exportaciones_metales_y_minerales.min(),rus.Exportaciones_metales_y_minerales.min(),esp.Exportaciones_metales_y_minerales.min()],
         "Exportaciones_metales_y_minerales max":[ch.Exportaciones_metales_y_minerales.max(),deu.Exportaciones_metales_y_minerales.max(),jpn.Exportaciones_metales_y_minerales.max(),gbr.Exportaciones_metales_y_minerales.max(),can.Exportaciones_metales_y_minerales.max(),usa.Exportaciones_metales_y_minerales.max(),mex.Exportaciones_metales_y_minerales.max(),fra.Exportaciones_metales_y_minerales.max(),bra.Exportaciones_metales_y_minerales.max(),arg.Exportaciones_metales_y_minerales.max(),rus.Exportaciones_metales_y_minerales.max(),esp.Exportaciones_metales_y_minerales.max()],
         "Exportaciones_combustibles min":[ch.Exportaciones_combustibles.min(),deu.Exportaciones_combustibles.min(),jpn.Exportaciones_combustibles.min(),gbr.Exportaciones_combustibles.min(),can.Exportaciones_combustibles.min(),usa.Exportaciones_combustibles.min(),mex.Exportaciones_combustibles.min(),fra.Exportaciones_combustibles.min(),bra.Exportaciones_combustibles.min(),arg.Exportaciones_combustibles.min(),rus.Exportaciones_combustibles.min(),esp.Exportaciones_combustibles.min()],
         "Exportaciones_combustibles max":[ch.Exportaciones_combustibles.max(),deu.Exportaciones_combustibles.max(),jpn.Exportaciones_combustibles.max(),gbr.Exportaciones_combustibles.max(),can.Exportaciones_combustibles.max(),usa.Exportaciones_combustibles.max(),mex.Exportaciones_combustibles.max(),fra.Exportaciones_combustibles.max(),bra.Exportaciones_combustibles.max(),arg.Exportaciones_combustibles.max(),rus.Exportaciones_combustibles.max(),esp.Exportaciones_combustibles.max()],
         "Importaciones_combustibles min": [ch.Importaciones_combustibles.min(), deu.Importaciones_combustibles.min(),jpn.Importaciones_combustibles.min(), gbr.Importaciones_combustibles.min(),can.Importaciones_combustibles.min(), usa.Importaciones_combustibles.min(),mex.Importaciones_combustibles.min(), fra.Importaciones_combustibles.min(),bra.Importaciones_combustibles.min(), arg.Importaciones_combustibles.min(),rus.Importaciones_combustibles.min(), esp.Importaciones_combustibles.min()],
         "Importaciones_combustibles max": [ch.Importaciones_combustibles.max(), deu.Importaciones_combustibles.max(),jpn.Importaciones_combustibles.max(), gbr.Importaciones_combustibles.max(),can.Importaciones_combustibles.max(), usa.Importaciones_combustibles.max(),mex.Importaciones_combustibles.max(), fra.Importaciones_combustibles.max(),bra.Importaciones_combustibles.max(), arg.Importaciones_combustibles.max(),rus.Importaciones_combustibles.max(), esp.Importaciones_combustibles.max()]
         }
todos = pd.DataFrame(todos)
print(todos[["Pais","Exportaciones_bienes_y_servicios max","Exportaciones_bienes_y_servicios min"]])


#todos.to_excel(r"C:\Users\resen\OneDrive\Documentos\5to Semestre\Ciencia de datos\Proyecto\ejemplo.xlsx", index=False, header=True)
#todos.to_csv(r"C:\Users\resen\OneDrive\Documentos\5to Semestre\Ciencia de datos\Proyecto\ejemplo.csv",index=False, header=True)